### ISSUE TITLE
SocureSigmaDeviceConfig limitation to use FragmentActivity

### ISSUE THREAD

**Issue by DanilKuhta** [socure-inc/socure-sigmadevice-sdk-android#11]
Is there any chance to change parameters in SocureSigmaDeviceConfig to use Activity or at least ComponentActivity instead of FragmentActivity? Not all the apps are using FragmentActivity nowadays. Thank you in advance.

**Comment by buraksocure** [comment]
Hi @DanilKuhta Thanks for your feedback. We added "FragmentActivity" to support Cross-Platforms like Flutter. So you can use either "AppCompatActivity()" or "FragmentActivity()" which also extends ComponentActivity. Let us know if you have any specific reason that you need ComponentActivity through our dse@socure.com email.
