### ISSUE TITLE
Post library to MavenCentral or other reliable repository

### ISSUE THREAD

**Issue by OSemenovBoyarka** [socure-inc/socure-sigmadevice-sdk-android#13]
Hello, currently SigmaDevice SDK is availabe only through jitpack.io package repository.
JitPack proved to be an unreliable option for enterprise projects and experienced multiple outages during last several months:
https://github.com/jitpack/jitpack.io/issues/5239
https://github.com/jitpack/jitpack.io/issues/5345
https://github.com/jitpack/jitpack.io/issues/5337
https://github.com/jitpack/jitpack.io/issues/5316

Socure library is the only dependency in our project, which is hosted on JitPack only, so it affects build stability. 
Could you host the SDK on the more reliable package repository, e.g. MavenCentral?

**Comment by rburunkayaSocure** [comment]
Hi @OSemenovBoyarka,

We are planning to start hosting SigmaDevice SDKs on Socure owned Maven repository. We are going to provide an update when new SigmaDevice SDKs arrives.

Kind regards,

**Comment by rburunkayaSocure** [comment]
Hi @OSemenovBoyarka,

We released Sigma Device Android SDKs v4.0.1 and started hosting SigmaDevice Android SDKs on Socure owned Maven repository.

Kind regards,
