### ISSUE TITLE
Sample app cannot be built.  

### ISSUE THREAD

**Issue by DougMcTuro** [socure-inc/socure-sigmadevice-sdk-android#17]
The sample app requires the following local properties to be defined:

```
buildConfigField "String", "SocurePublicKey", localProperties['socure.public.key']
buildConfigField "String", "idPlusKey", localProperties['id.plus.key']
buildConfigField "String", "CERT_PIN_SOCURE", localProperties['cert.pin.socure']
buildConfigField "String", "CERT_PIN_AMAZON_INTERMEDIATE", localProperties['cert.pin.amazon.intermediate']
buildConfigField "String", "CERT_PIN_AMAZON_ROOT", localProperties['cert.pin.amazon.root']
```
The readme does not indicate where to find these values.  

Additionally, building the project without these produces the error:
`Could not GET 'https://jitpack.io/com/github/socure-inc/device-risk-android-sdk/3.0.0/device-risk-android-sdk-3.0.0.pom'. Received status code 401 from server: Unauthorized`

If this sample code is intended to be used only by certain privileged users, can the readme be updated to indicate as much?

**Comment by rburunkayaSocure** [comment]
Hi @DougMcTuro ,

Please send an email to dse@socure.com to discuss further and happy to provide instructions.

Kind regards
